// Generated by Wrangler on Wed May 15 2024 12:02:31 GMT-0600 (Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	WORKER_ENV: "local";
	DB: D1Database;
}
