import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { RootHeader } from '@/components/root-header';
import { ThemeProvider } from '@/components/theme-provider';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/*Async components in layout must be wrapped inside suspense !!!*/}
          <Suspense>
            <RootHeader />
          </Suspense>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
